image: gitpod/workspace-full:latest

tasks:
  - name: initial
    init: go install github.com/go-task/task/v3/cmd/task@latest &&
      brew install hyperfine &&
      python -m pip install bpython
    command: python --version
